// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aubiqapmeihzkamqdxhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1YmlxYXBtZWloemthbXFkeGhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjM4NjQsImV4cCI6MjA2MjE5OTg2NH0.2bEuxCUiZICGddIxRxODqTwQWUccEm5u9AYgk8FVZQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);